"""empty message

Revision ID: a645bdb225b4
Revises: f44ca1e95561
Create Date: 2024-09-12 15:28:49.136924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a645bdb225b4'
down_revision = 'f44ca1e95561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
